# Файл сборки Docker контейнера проекта

# Установка образа и рабочей директории
FROM node:lts-buster-slim
WORKDIR /usr/src/app


# Установка зависимостей
COPY package.json .
RUN npm install

# Добавление оставшихся файлов проекта
COPY tsconfig.json .
ADD bot bot


# Объявление переменных окружения
ARG BOT_TOKEN

# Имена подключаемых баз данных внутри контейнера
ENV BOT_DB_PATH="bot_db.sqlite"
ENV ORG_DB_PATH="org_db.sqlite"


# Запуск контейнера
CMD npm run start